---
title: "Observations on the optimization process"
author: "Cristhian Paredes and Jesús Ágreda"
date: "`r Sys.Date()`"
output: 
  knitr:::html_vignette:
    toc: true
    fig_caption: yes
  pdf_document:
    highlight: null
    number_sections: yes
vignette: >
  %\VignetteIndexEntry{labsimplexModelSurface}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  out.width = "48%"
)
# Render html vignetes by using devtools::document(roclets = "vignette")
# Render also pdf vignetes by using rmarkdown::render("vignettes/labsimplex.Rmd", "all")
require(labsimplex)
require(ggplot2)
```

```{r functions, echo = FALSE}
prspctv <- function (length, noise) {
  temp <- x <- seq(278, 365, length = length)
  pH <- y <- seq(0, 14, length = length)
  z <- outer(x, y, exampleSurfaceR2.2pks, noise = noise)
  
  colors  <- colorRampPalette(c("grey30", "white"))(100)
  z.facet.center <- (z[-1, -1] + z[-1, -ncol(z)] + z[-nrow(z), -1] + z[-nrow(z), -ncol(z)])/4
  z.facet.range  <- cut(z.facet.center, 200)
  persp(x, y, z, theta = 22, phi = 15, ticktype = "detailed", col = colors[z.facet.range], lwd = 0.3,
        ltheta = -120, shade = 0.2, expand = 0.6, xlab = 'Temperature (K)', ylab = 'pH', zlab = 'Yield (%)')
}
cntr <- function (length, noise) {
  x <- seq(278, 365, length = length)
  y <- seq(0, 14, length = length)
  gg <- expand.grid(x = x, y = y)
  gg$z <- with(gg, exampleSurfaceR2.2pks(x, y, noise = noise))
  
  #brks <- cut(gg$z, breaks = seq(0, 100, len = 10))
brks <- cut(gg$z, breaks = seq(0, 90, 10))
brks <- gsub(",", " - ", brks, fixed = TRUE)
gg$brks <- gsub("\\(|\\]", "", brks)  # reformat guide labels
p <- ggplot(gg, aes(x, y)) + theme_bw() +
       geom_tile(aes(fill = brks)) + scale_fill_manual("Z", values = colorRampPalette(c("grey30", "white"))(11)) +
       scale_x_continuous(expand = c(0, 0), limits = c(278, 365)) + scale_y_continuous(expand = c(0, 0), limits = c(0, 14)) +
       theme(legend.position = 'none', axis.text = element_text(size = 12, color = 'black'),
             axis.title = element_text(size = 12, color = 'black'), plot.margin = unit(c(0.5, 0.5, 0.1, 0.1), "cm"),
             panel.border = element_blank(), panel.grid.major = element_blank(),
             panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + 
       labs(x = 'Temperature (K)', y = 'pH')
  return(p)
}
#cntrOLD <- function (length, noise) {
#  require(lattice)
#    x <- seq(280, 360, length = length)
#    y <- seq(1, 13, length = length)
#    df <- data.frame(expand.grid(x, y), exmplsurface(x = expand.grid(x, y)[, 1], y = expand.grid(x, y)[, 2], noise = noise))
#    colnames(df) <- c('x', 'y', 'z')
#    contourplot(z ~ x * y, df, lwd = 0.7, cuts = 10, labels = FALSE, region = TRUE,
#                col.regions = colorRampPalette(c("grey10", "white")),
#                xlab = 'Temperature (K)', ylab = 'pH', zlab = 'Yield (%)')
#}
completeOptimization <- function (centroid, stepsize = c(0.6, 10), algor = 'fixed', experiments = 17,
                                  length = 300, noise = 0) {
  simplex <- labsimplex(N = 2, centroid = centroid, stepsize = stepsize, var.name = c('pH', 'Temperature'))
  for (ii in 1:experiments){
    if (ii == 1) {
      simplex <- generateVertex(simplex = simplex, algor = algor,
                                qflv = exampleSurfaceR2.2pks(temp = simplex$coords[, 2], pH = simplex$coords[, 1]))
    } else {
      simplex <- generateVertex(simplex = simplex, algor = algor,
                                qflv = exampleSurfaceR2.2pks(temp = simplex$coords[nrow(simplex$coords), 2], 
                                                     pH = simplex$coords[nrow(simplex$coords), 1]))
    }
  }
  p <- cntr(length = length, noise = noise) + geom_point(data = data.frame(x = simplex$coords[, 2], y = simplex$coords[, 1]))
  V.pos <- as.numeric(gsub("Vertex.", "", row.names(simplex$coords)))
  x <- xend <- y <- yend <- vector()
  for (ii in 1:length(simplex$families)) {
    for (jj in 1:(length(simplex$families[[ii]]) - 1)) {
      for (kk in (jj + 1):length(simplex$families[[ii]])) {
        jj. <- which(simplex$families[[ii]][jj] == V.pos)
        kk. <- which(simplex$families[[ii]][kk] == V.pos)
        x    <- c(x, simplex$coords[jj., 2])
        xend <- c(xend, simplex$coords[kk., 2])
        y    <- c(y, simplex$coords[jj., 1])
        yend <- c(yend, simplex$coords[kk., 1])
      }
    }
  }
  p <- p + geom_segment(data = data.frame(x = x, xend = xend, y = y, yend = yend),
                        aes(x = x, xend = xend, y = y, yend = yend))
  print(p)
}

```
## Introduction
This vignette ... ...

## Response surface studied
The response surface below is 

```{r plotsWOnoise, echo = FALSE}
  par(mar = c(1, 1, 0, 0))
  prspctv(length = 45, noise = 0)
  print(cntr(length = 350, noise = 0))
```

## Finding the *nearest* local optima
```{r LocalOptima, echo = FALSE, results = 'hide', message = FALSE, warning = FALSE}
completeOptimization(centroid = c(3, 290), stepsize = c(1.5, 15), experiments = 15)
completeOptimization(centroid = c(12, 335), stepsize = c(1.5, 15), experiments = 12)
completeOptimization(centroid = c(1.5, 310), stepsize = c(1.5, 15), experiments = 12)
completeOptimization(centroid = c(5.5, 315), stepsize = c(-1.5, 15), experiments = 12)

completeOptimization(centroid = c(3, 290), stepsize = c(1.5, 15), experiments = 18, algor = 'variable')
completeOptimization(centroid = c(12, 335), stepsize = c(1.5, 15), experiments = 18, algor = 'variable')
completeOptimization(centroid = c(1.5, 310), stepsize = c(1.5, 15), experiments = 15, algor = 'variable')
completeOptimization(centroid = c(5.5, 315), stepsize = c(-1.5, 15), experiments = 15, algor = 'variable')


```

## Noisy response surface
```{r plotsW2noise, echo = FALSE}
  par(mar = c(1, 1, 0.1, 0.1))
  #plot1 <- prspctv(length = 45, noise = 2)
  #plot2 <- cntr(length = 45, noise = 2)
  #print(plot2)
```
```{r plotsW4noise, echo = FALSE}
  par(mar = c(1, 1, 0.1, 0.1))
  #plot1 <- prspctv(length = 45, noise = 7)
  #plot2 <- cntr(length = 45, noise = 7)
  #plot2 <- cntr(length = 45, noise = 7)
  #print(plot2)
```
```{r plotsW7noise, echo = FALSE}
  par(mar = c(1, 1, 0.1, 0.1))
  #plot1 <- prspctv(length = 45, noise = 10)
  #plot2 <- cntr(length = 45, noise = 10)
  #print(plot2)
```
  
